<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36" started-at="2019-10-15T16:40:21Z" finished-at="2019-10-15T16:40:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36" started-at="2019-10-15T16:40:21Z" finished-at="2019-10-15T16:40:21Z">
      <class name="git_test.Test_helloword">
        <test-method status="FAIL" signature="add_string_test()[pri:0, instance:git_test.Test_helloword@74895110]" name="add_string_test" duration-ms="16" started-at="2019-10-16T00:40:21Z" finished-at="2019-10-16T00:40:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [xiwa] but found [xiwa_test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [xiwa] but found [xiwa_test]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at git_test.Test_helloword.add_string_test(Test_helloword.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_string_test -->
        <test-method status="PASS" signature="f()[pri:0, instance:git_test.Test_helloword@74895110]" name="f" duration-ms="1" started-at="2019-10-16T00:40:21Z" finished-at="2019-10-16T00:40:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- git_test.Test_helloword -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
